use std::time::Instant;
use tracing::{info, warn};

use acpi_tables::Aml;
use acpi_tables::rsdp::Rsdp;
use acpi_tables::sdt::{GenericAddress, Sdt};
use zerocopy::IntoBytes;
use zerocopy_derive::{Immutable, FromBytes};

use crate::cpu::CpuManager;
use crate::device_manager::{DeviceManager, PciSegment};
use crate::devices::bus::BusDevice;
use crate::memory::memory::{GuestAddress, MemoryManager};
use crate::memory::layout::RSDP_POINTER;

const FACP_DSDT_OFFSET: usize = 140;

pub struct AcpiPlatformAddresses {
    pub pm_timer_address: Option<GenericAddress>,
    pub reset_reg_address: Option<GenericAddress>,
    pub sleep_control_reg_address: Option<GenericAddress>,
    pub sleep_status_reg_address: Option<GenericAddress>,
}

impl AcpiPlatformAddresses {
    pub fn new() -> Self {
        Self {
            pm_timer_address: None,
            reset_reg_address: None,
            sleep_control_reg_address: None,
            sleep_status_reg_address: None,
        }
    }
}

#[derive(Default, IntoBytes, Immutable, FromBytes)]
struct PciRangeEntry {
    pub base_address: u64,
    pub segment: u16,
    pub start: u8,
    pub end: u8,
    _reserved: u32,
}

pub fn create_dsdt_table(
    device_manager: &DeviceManager,
    cpu_manager: &CpuManager,
) -> Sdt {
    info!("create_dsdt_table");
    // DSDT
    let mut dsdt = Sdt::new(*b"DSDT", 36, 6, *b"CLOUDH", *b"CHDSDT  ", 1);

    let mut bytes = Vec::new();

    device_manager.to_aml_bytes(&mut bytes);
    cpu_manager.to_aml_bytes(&mut bytes);
    dsdt.append_slice(&bytes);

    dsdt
}

fn create_facp_table(dsdt_offset: GuestAddress, device_manager: &DeviceManager) -> Sdt {
    info!("create_facp_table");

    // Revision 6 of the ACPI FADT table is 276 bytes long
    let mut facp = Sdt::new(*b"FACP", 276, 6, *b"CLOUDH", *b"CHFACP  ", 1);

    if let Some(address) = device_manager.acpi_platform_addresses().reset_reg_address {
        // RESET_REG
        facp.write(116, address);
        // RESET_VALUE
        facp.write(128, 1u8);
    }

    if let Some(address) = device_manager
        .acpi_platform_addresses()
        .sleep_control_reg_address
    {
        // SLEEP_CONTROL_REG
        facp.write(244, address);
    }

    if let Some(address) = device_manager
        .acpi_platform_addresses()
        .sleep_status_reg_address
    {
        // SLEEP_STATUS_REG
        facp.write(256, address);
    }

    if let Some(address) = device_manager.acpi_platform_addresses().pm_timer_address {
        // X_PM_TMR_BLK (extended 64-bit Generic Address Structure)
        facp.write(208, address);
        // PM_TMR_BLK (legacy 32-bit I/O port address, offset 76)
        facp.write(76, 0x608u32);
    }
    
    facp.write(91, 4u8); // PM_TMR_LEN (offset 91) - 4 bytes for PM timer register block

    // Architecture common fields
    // HW_REDUCED_ACPI (bit 20), TMR_VAL_EXT (bit 10), RESET_REG_SUP (bit 8)
    let fadt_flags: u32 = (1 << 20) | (1 << 10) | (1 << 8);
    facp.write(112, fadt_flags);
    // FADT minor version
    facp.write(131, 3u8);
    // X_DSDT
    facp.write(FACP_DSDT_OFFSET, dsdt_offset.0);
    // Hypervisor Vendor Identity
    facp.write_bytes(268, b"CLOUDHYP");

    facp.update_checksum();

    facp
}

fn create_mcfg_table(pci_segments: &[PciSegment]) -> Sdt {
    info!("create_mcfg_table");
    let mut mcfg = Sdt::new(*b"MCFG", 36, 1, *b"CLOUDH", *b"CHMCFG  ", 1);

    // MCFG reserved 8 bytes
    mcfg.append(0u64);

    for segment in pci_segments {
        // 32-bit PCI enhanced configuration mechanism
        mcfg.append(PciRangeEntry {
            base_address: segment.get_mmio_config_address(),
            segment: segment.get_id(),
            start: 0,
            end: 255,
            ..Default::default()
        });
    }

    mcfg.update_checksum();
    mcfg
}

// Generate ACPI tables based on the given DSDT address
//
// # Returns
//
// * `Rsdp` is the generated RSDP.
// * `Vec<u8>` contains the generated bytes for ACPI tables.
// * `Vec<u64>` contains a list of table pointers stored in XSDT.
fn create_acpi_tables_internal(
    dsdt_addr: GuestAddress,
    device_manager: &DeviceManager,
    cpu_manager: &CpuManager
) -> (Rsdp, Vec<u8>, Vec<u64>) {
    // Generated bytes for ACPI tables
    let mut tables_bytes: Vec<u8> = Vec::new();
    // List of table pointers stored in XSDT
    let mut xsdt_table_pointers: Vec<u64> = Vec::new();

    // 1. DSDT (Hardware description)
    let dsdt = create_dsdt_table(device_manager, cpu_manager);
    tables_bytes.extend_from_slice(dsdt.as_slice());

    // 2. FADT (Power/DSDT pointer)
    let facp = create_facp_table(dsdt_addr, device_manager);
    let facp_addr = dsdt_addr.0.checked_add(dsdt.len() as u64).unwrap();
    tables_bytes.extend_from_slice(facp.as_slice());
    xsdt_table_pointers.push(facp_addr);

    // 3. MADT (Interrupts/CPUs)
    let madt = cpu_manager.create_madt();
    let madt_addr = facp_addr.checked_add(facp.len() as u64).unwrap();
    tables_bytes.extend_from_slice(madt.as_slice());
    xsdt_table_pointers.push(madt_addr);
    let mut prev_tbl_len = madt.len() as u64;
    let mut prev_tbl_addr = madt_addr;

    // 4. MCFG (PCIe Config Space)
    let mcfg = create_mcfg_table(device_manager.pci_segments());
    let mcfg_addr = prev_tbl_addr.checked_add(prev_tbl_len).unwrap();
    tables_bytes.extend_from_slice(mcfg.as_slice());
    xsdt_table_pointers.push(mcfg_addr);
    prev_tbl_len = mcfg.len() as u64;
    prev_tbl_addr = mcfg_addr;
    
    // 5. XSDT (Pointer to 2, 3, 4)
    let mut xsdt = Sdt::new(*b"XSDT", 36, 1, *b"CLOUDH", *b"CHXSDT  ", 1);
    for table_pointer in &xsdt_table_pointers {
        xsdt.append(*table_pointer);
    }
    xsdt.update_checksum();
    let xsdt_addr = prev_tbl_addr.checked_add(prev_tbl_len).unwrap();
    tables_bytes.extend_from_slice(xsdt.as_slice());

    // 6. RSDP (Pointer to 5)
    let rsdp = Rsdp::new(*b"CLOUDH", xsdt_addr);

    (rsdp, tables_bytes, xsdt_table_pointers)
}

pub fn create_acpi_tables(
    device_manager: &DeviceManager,
    cpu_manager: &CpuManager,
    memory_manager: &MemoryManager
) -> GuestAddress {
    info!("create_acpi_tables");

    let start_time = Instant::now();
    let rsdp_addr = RSDP_POINTER;
    let dsdt_addr = GuestAddress(rsdp_addr.0.checked_add(Rsdp::len() as u64).unwrap());

    let (rsdp, tables_bytes, _xsdt_table_pointers) = create_acpi_tables_internal(
        dsdt_addr,
        device_manager,
        cpu_manager,
    );

    let _ = memory_manager.write_guest_memory(&rsdp.as_bytes(), rsdp_addr);
    let _ = memory_manager.write_guest_memory(&tables_bytes.as_slice(), dsdt_addr);

    info!(
        "Generated ACPI tables: took {}µs size = {}",
        Instant::now().duration_since(start_time).as_micros(),
        Rsdp::len() + tables_bytes.len(),
    );

    rsdp_addr
}

pub struct AcpiPmTimerDevice {
    start: Instant,
}

impl AcpiPmTimerDevice {
    pub fn new() -> Self {
        Self {
            start: Instant::now(),
        }
    }
}

impl BusDevice for AcpiPmTimerDevice {
    fn read(&mut self, _base: u64, _offset: u64, data: &mut [u8]) {
        // Only supports 32-bit reads
        if data.len() != std::mem::size_of::<u32>() {
            warn!("Invalid sized read of PM timer: {}", data.len());
            return;
        }
        
        // Calculate elapsed time since device creation
        let now = Instant::now();
        let since = now.duration_since(self.start);
        let nanos = since.as_nanos();
        
        // Convert to PM timer ticks (3.579545 MHz)
        const PM_TIMER_FREQUENCY_HZ: u128 = 3_579_545;
        const NANOS_PER_SECOND: u128 = 1_000_000_000;
        
        let counter = (nanos * PM_TIMER_FREQUENCY_HZ) / NANOS_PER_SECOND;
        let counter: u32 = (counter & 0xffff_ffff) as u32; // 32-bit wrap
        
        // Return as little-endian bytes
        data.copy_from_slice(&counter.to_le_bytes());
    }
}